version: "3.3"

services:
  meilisearch:
    container_name: "search.f6sny.com"
    image: "getmeili/meilisearch:v0.26.1"
    restart: unless-stopped
    ports:
      - "7700:7700"
    volumes:
      - /var/local/meilisearch:/data.ms
    #env_file:
    #  - ./meilisearch.env
