version: "3.9"

services:
  meilisearch:
    image: "getmeili/meilisearch:v0.26.1"
    restart: unless-stopped
    ports:
      - "7700:7700"
    volumes:
      - /var/local/meilisearch:/data.ms
    env_file:
      - ./meilisearch.env
